# VoidOS — Limine v9.x boot configuration
# x86_64 long mode, 4-level paging

timeout: 3
verbose: yes

/VoidOS
    protocol: limine
    kernel_path: boot():/boot/voidos.elf
    # Module type 0x01: initial userland image (Process 1 / Init)
    # module_path: boot():/boot/userland.img
    # module_cmdline: type=0x01
    # Module type 0x02: system services / drivers (Ring 3 modules)
    # module_path: boot():/boot/drivers/abc.ss
    # module_cmdline: type=0x02
